version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ckeditor
    versions:
    - ">= 5.a, < 6"
  - dependency-name: json-schema
    versions:
    - "> 2.8.0, < 2.9"
  - dependency-name: rack
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: sprockets
    versions:
    - ">= 4.a, < 5"
  - dependency-name: sidekiq-unique-jobs
    versions:
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
  - dependency-name: oj
    versions:
    - 3.11.3
    - 3.11.4
  - dependency-name: aws-sdk-s3
    versions:
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: rubocop
    versions:
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rubocop-performance
    versions:
    - 1.10.2
  - dependency-name: bootsnap
    versions:
    - 1.7.2
    - 1.7.3
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: appsignal
    versions:
    - 2.11.9
    - 3.0.0
    - 3.0.1
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: rails
    versions:
    - 5.2.4.5
  - dependency-name: puma
    versions:
    - 5.2.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
