// this file is generated by gis/getContextMaps.sh
const contextLayersCarto = {
  brazil_states: {
    uid: 'brazil_states1525877779258',
    layergroupid: 'p2cs-sei@4f66c3f4@680afab6affbf91c4c47b9fdb3b1829d:1525368076102'
  },
  brazil_biomes: {
    uid: 'brazil_biomes1525877785816',
    layergroupid: 'p2cs-sei@c1d71b95@79bf0c435393606e5a1e58d26964eaa7:1525368086905'
  },
  water_scarcity: {
    uid: 'water_scarcity1525877786881',
    layergroupid: 'p2cs-sei@5ffc14cf@14437ab7b0257eb039281ab98c8ab803:1525368081340'
  },
  indigenous_areas: {
    uid: 'indigenous_areas1525877793015',
    layergroupid: 'p2cs-sei@2cadcf6e@405424b2a986ffbaafd3f7f8c53d9b42:1525368083151'
  },
  brazil_protected: {
    uid: 'brazil_protected1525877794171',
    layergroupid: 'p2cs-sei@8908ddf6@0099b40a158ad09b7378f17fec3bb458:1525368077101'
  },
  brazil_defor_alerts: {
    uid: 'brazil_defor_alerts1525877795440',
    layergroupid: 'p2cs-sei@3a56c0ab@43cb8a7ae9c62eb1eac03529a9d9c924:1525368094112'
  }
};
export default contextLayersCarto;
