// this file is generated by gis/named-maps.js
module.exports = {
  production: {
    brazil_states: {
      uid: 'brazil_states__production',
      layergroupid: 'p2cs-sei@4f456911@94bb9db1cc2bbb6f823b52891ea85a4b:1536754740910'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__production',
      layergroupid: 'p2cs-sei@ee8b4bf2@53eff313f97bb4d6e956f5078a2ce178:1536754747512'
    },
    brazil_water_scarcity: {
      uid: 'brazil_water_scarcity__production',
      layergroupid: 'p2cs-sei@ce96a651@bd75df185965352f558793d64c6c76af:1536754755124'
    },
    brazil_indigenous_areas: {
      uid: 'brazil_indigenous_areas__production',
      layergroupid: 'p2cs-sei@bef64c15@b9f9b57ffb78da8860a82269aa5673aa:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__production',
      layergroupid: 'p2cs-sei@851f6bd9@124c2f3d625b7192f32bb55a83a8b2fd:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__production',
      layergroupid: 'p2cs-sei@c4807a94@9495c323e40ff63e0c59e0fc6ffbebcd:1538401614852'
    }
  },
  development: {
    brazil_states: {
      uid: 'brazil_states__development',
      layergroupid: 'p2cs-sei@79d8b6c4@5d0ad8d7fce54c67b90308a8db45756f:1525368076102'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__development',
      layergroupid: 'p2cs-sei@53496782@af95c2a43027d24c22f3fe1c6c55db63:1536754747512'
    },
    water_scarcity: {
      uid: 'water_scarcity__development',
      layergroupid: 'p2cs-sei@99a5121a@402f2b1ec6819c0cabfea31443a30cf9:1536754755124'
    },
    indigenous_areas: {
      uid: 'indigenous_areas__development',
      layergroupid: 'p2cs-sei@969e9936@8c3a951aa209095a67b324ce57666eb4:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__development',
      layergroupid: 'p2cs-sei@d188e3b2@27f877278755b535e88ccacee214beb7:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__development',
      layergroupid: 'p2cs-sei@8a7654c3@a916e3ed49a3a4095612d7ca6266c3ef:1525368094112'
    },
    col_protected_areas: {
      uid: 'col_protected_areas__development',
      layergroupid: 'p2cs-sei@ef891231@00901bb55c96b2ce22481f4f643cd663:1537979981544'
    },
    col_adm1_1: {
      uid: 'col_adm1_1__development',
      layergroupid: 'p2cs-sei@7bcc1cb8@79f63682d3c8a33bf661ad8ef0cb515b:1525368093739'
    }
  },
  sandbox: {
    brazil_states: {
      uid: 'brazil_states__sandbox',
      layergroupid: 'p2cs-sei@813fddd3@cc7c9866165bd98a1fdd4113ec31ac49:1536754740910'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__sandbox',
      layergroupid: 'p2cs-sei@c93b6cad@5a3d352564249dd7eaf1f5a2271b471d:1536754747512'
    },
    brazil_water_scarcity: {
      uid: 'brazil_water_scarcity__sandbox',
      layergroupid: 'p2cs-sei@51aab8e1@4ee3434d572f8071c4ee8395cd84c069:1536754755124'
    },
    brazil_indigenous_areas: {
      uid: 'brazil_indigenous_areas__sandbox',
      layergroupid: 'p2cs-sei@99f56118@ef8eae3b879a710a3772c7a5f1e34eae:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__sandbox',
      layergroupid: 'p2cs-sei@94358e00@27478e79b3971e23f86bccc8aae4b0e1:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__sandbox',
      layergroupid: 'p2cs-sei@d3572a6b@119855d12a08daf809c7911fb721a04c:1538401614852'
    }
  },
  demo: {
    paraguay_ecoregions_2018_11_14: {
      uid: 'paraguay_ecoregions_2018_11_14__demo',
      layergroupid: 'p2cs-sei@994d4ecc@e6242c89e7af7c01ad3c7286e7f8e75f:1543380503816'
    },
    paraguay_protected_areas_2018_11_14: {
      uid: 'paraguay_protected_areas_2018_11_14__demo',
      layergroupid: 'p2cs-sei@4a6b05f7@ab6d3ac3380c73c9eddce074e6ddfb84:1542212474275'
    },
    paraguay_indigenous_areas_2018_11_14: {
      uid: 'paraguay_indigenous_areas_2018_11_14__demo',
      layergroupid: 'p2cs-sei@57f269c7@875c2a005b56193dc66f5aafb3dd808b:1542212565695'
    },
    col_departments: {
      uid: 'col_departments__demo',
      layergroupid: 'p2cs-sei@ac7a49be@5ae47ae98e8070dbc3983e87100857c9:1525368093739'
    },
    paraguay_deforestation_2017_2018_11_15: {
      uid: 'paraguay_deforestation_2017_2018_11_15__demo',
      layergroupid: 'p2cs-sei@2f21313c@cbeebda836abe3d170b8e3d750a24eb5:1542298677399'
    }
  }
};
