// this file is generated by gis/named-maps.js
module.exports = {
  production: {
    brazil_states: {
      uid: 'brazil_states1538040623401',
      layergroupid: 'p2cs-sei@5f503d7c@ad9947aed69ba64bb275829c43505e45:1525368076102'
    },
    brazil_biomes: {
      uid: 'brazil_biomes1538040624445',
      layergroupid: 'p2cs-sei@76cc05f0@80e0824f230b00c7b8d58beaaeb520d8:1536754747512'
    },
    water_scarcity: {
      uid: 'water_scarcity1538040625290',
      layergroupid: 'p2cs-sei@b74e67c2@309c4fc88126169c70ae0a2d80abb2d0:1536754755124'
    },
    indigenous_areas: {
      uid: 'indigenous_areas1538040626144',
      layergroupid: 'p2cs-sei@5ffb143b@d0af2032fe70f7cf11e53c24017d2a1b:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected1538040627004',
      layergroupid: 'p2cs-sei@5d4f9d60@510b43b8a25a0053e13e90135955fee0:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts1538040627875',
      layergroupid: 'p2cs-sei@89f013b7@f2c183cc1c4ff03128c333156e32e236:1525368094112'
    },
    col_protected_areas: {
      uid: 'col_protected_areas1538040628734',
      layergroupid: 'p2cs-sei@fa1d57ed@c1cfe7a14d3a25fe34899d40a737a29b:1537979981544'
    },
    col_adm1_1: {
      uid: 'col_adm1_11538040629580',
      layergroupid: 'p2cs-sei@bbb977bf@fc3af4c09050cd0a896103344de12ac0:1525368093739'
    }
  },
  development: {
    brazil_states: {
      uid: 'brazil_states__development',
      layergroupid: 'p2cs-sei@79d8b6c4@5d0ad8d7fce54c67b90308a8db45756f:1525368076102'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__development',
      layergroupid: 'p2cs-sei@53496782@af95c2a43027d24c22f3fe1c6c55db63:1536754747512'
    },
    water_scarcity: {
      uid: 'water_scarcity__development',
      layergroupid: 'p2cs-sei@99a5121a@402f2b1ec6819c0cabfea31443a30cf9:1536754755124'
    },
    indigenous_areas: {
      uid: 'indigenous_areas__development',
      layergroupid: 'p2cs-sei@969e9936@8c3a951aa209095a67b324ce57666eb4:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__development',
      layergroupid: 'p2cs-sei@d188e3b2@27f877278755b535e88ccacee214beb7:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__development',
      layergroupid: 'p2cs-sei@8a7654c3@a916e3ed49a3a4095612d7ca6266c3ef:1525368094112'
    },
    col_protected_areas: {
      uid: 'col_protected_areas__development',
      layergroupid: 'p2cs-sei@ef891231@00901bb55c96b2ce22481f4f643cd663:1537979981544'
    },
    col_adm1_1: {
      uid: 'col_adm1_1__development',
      layergroupid: 'p2cs-sei@7bcc1cb8@79f63682d3c8a33bf661ad8ef0cb515b:1525368093739'
    }
  }
};
