version: '2' # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-10
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - app/controllers/
      - app/admin/api/v3/
      - app/models/actor_attributes.rb
      - app/models/place_attributes.rb
      - app/models/node.rb
      - app/models/node_ind.rb
      - app/models/node_qual.rb
      - app/models/node_quant.rb
      - app/models/flow_stats_for_node.rb
      - app/models/node_type.rb
    config:
      languages:
      - ruby:
  apexmetrics:
    enabled: true
  reek:
    enabled: true

exclude_patterns:
- "db/**/*"
- "lib/db_helpers/**/*" # db helpers, mostly temporary
- "spec/**/*"
- "**/vendor/**/*"
