engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - app/admin/api/v3/
    config:
      languages:
      - ruby:
  apexmetrics:
    enabled: true
  reek:
    enabled: true
    checks:
      UncommunicativeModuleName:
        enabled: false
      IrresponsibleModule:
        enabled: false

ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- db/**/*
- 'lib/schema_revamp.rb' # excluding because it is a temporary migration script
- 'lib/schema_content.rb' # excluding because it is a temporary migration script
- 'lib/db_helpers/**/*' # db helpers, mostly temporary
