inherit_from: .rubocop_todo.yml

require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/scripts/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'
    - 'frontend/node_modules/**/*'
