fix: false
parallel: true
format: progress
ruby_version: 3.1.0
default_ignores: false

ignore:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'db/schema.rb'
  - 'db/migrate/*'
  - 'db/scripts/*'
  - 'frontend/node_modules/**/*'
  - 'app/services/api/v3/places/basic_attributes.rb'
