class NodeTypeName < EnumerateIt::Base
  associate_values(
    BIOME: "BIOME",
    STATE: "STATE",
    LOGISTICS_HUB: "LOGISTICS HUB",
    MUNICIPALITY: "MUNICIPALITY",
    EXPORTER: "EXPORTER",
    PORT_OF_EXPORT: "PORT OF EXPORT",
    PORT: "PORT",
    IMPORTER: "IMPORTER",
    COUNTRY: "COUNTRY",
    TRADER: "TRADER",
    DEPARTMENT: "DEPARTMENT",
    COUNTRY_OF_DESTINATION: "COUNTRY OF DESTINATION",
    COUNTRY_OF_IMPORT: "COUNTRY OF IMPORT",
    COUNTRY_OF_FIRST_IMPORT: "COUNTRY OF FIRST IMPORT",
    COUNTRY_OF_PRODUCTION: "COUNTRY OF PRODUCTION",
    CUSTOMS_DEPARTMENT: "CUSTOMS DEPARTMENT",
    ECONOMIC_BLOC: "ECONOMIC BLOC"
  )

  def self.destination_country_names
    [COUNTRY, COUNTRY_OF_IMPORT, COUNTRY_OF_FIRST_IMPORT, COUNTRY_OF_DESTINATION]
  end
end
