// this file is generated by /Users/rodrigo/WorkWorkWorkWorkWork/trase/frontend/gis/cartodb/named-maps.js
module.exports = {
  production: {
    brazil_states: {
      uid: 'brazil_states__production',
      layergroupid: 'p2cs-sei@4f456911@94bb9db1cc2bbb6f823b52891ea85a4b:1536754740910'
    },
    brazil_water_scarcity: {
      uid: 'brazil_water_scarcity__production',
      layergroupid: 'p2cs-sei@ce96a651@bd75df185965352f558793d64c6c76af:1536754755124'
    },
    brazil_indigenous_areas: {
      uid: 'brazil_indigenous_areas__production',
      layergroupid: 'p2cs-sei@bef64c15@b9f9b57ffb78da8860a82269aa5673aa:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__production',
      layergroupid: 'p2cs-sei@851f6bd9@124c2f3d625b7192f32bb55a83a8b2fd:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__production',
      layergroupid: 'p2cs-sei@c4807a94@9495c323e40ff63e0c59e0fc6ffbebcd:1538401614852'
    },
    paraguay_protected_areas_2018_11_14: {
      uid: 'paraguay_protected_areas_2018_11_14__production',
      layergroupid: 'p2cs-sei@7fb7d231@e3a7e457c532b2340f2fa76d05c84160:1542212474275'
    },
    py_deforestation_2013_2017_20190131: {
      uid: 'py_deforestation_2013_2017_20190131__production',
      layergroupid: 'p2cs-sei@9d6ad933@07588ca1af7caf72f3f838cdac1cac8f:1548926222884'
    },
    colombia_regional_autonomous_corps: {
      uid: 'colombia_regional_autonomous_corps__production',
      layergroupid: 'p2cs-sei@503b6857@c4c1c3f71af8652b5e4a4ebf8ea6d344:1536313111531'
    },
    colombia_protected_areas: {
      uid: 'colombia_protected_areas__production',
      layergroupid: 'p2cs-sei@bd5844b5@7068763bcb727c705c489c838b6deadb:1536312121956'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__production',
      layergroupid: 'p2cs-sei@ee8b4bf2@53eff313f97bb4d6e956f5078a2ce178:1536754747512'
    },
    paraguay_ecoregions_2018_11_14: {
      uid: 'paraguay_ecoregions_2018_11_14__production',
      layergroupid: 'p2cs-sei@8bc16e3e@920a70ce8cd9698d474541a13571868e:1543380503816'
    },
    paraguay_indigenous_areas_2018_11_14: {
      uid: 'paraguay_indigenous_areas_2018_11_14__production',
      layergroupid: 'p2cs-sei@93c53b34@286bbb73f3bcdfa206205acef80ec835:1542212565695'
    }
  },
  development: {
    brazil_states: {
      uid: 'brazil_states__development',
      layergroupid: 'p2cs-sei@b06a355d@9de41b35f0a1b60b2aa10c17d425647a:1536754740910'
    },
    brazil_biomes: {
      uid: 'brazil_biomes__development',
      layergroupid: 'p2cs-sei@1392c7ac@ede5da577e49c54cae5f5d285a37839d:1536754747512'
    },
    brazil_water_scarcity: {
      uid: 'brazil_water_scarcity__development',
      layergroupid: 'p2cs-sei@f906de3a@dc3fa18c3568bdf183f83eceddeaa8f4:1536754755124'
    },
    brazil_indigenous_areas: {
      uid: 'brazil_indigenous_areas__development',
      layergroupid: 'p2cs-sei@2bf1234d@b2952f7aa00e10ee10bb538fd5d5ab27:1538034854446'
    },
    brazil_protected: {
      uid: 'brazil_protected__development',
      layergroupid: 'p2cs-sei@d188e3b2@27f877278755b535e88ccacee214beb7:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__development',
      layergroupid: 'p2cs-sei@082e3a98@a2f2a0645bced22e2aaf17ddda69a24f:1538401614852'
    },
    paraguay_ecoregions_2018_11_14: {
      uid: 'paraguay_ecoregions_2018_11_14__development',
      layergroupid: 'p2cs-sei@cc63f9d1@eeddac7b409e4b6277bed45205d70c37:1543380503816'
    },
    paraguay_protected_areas_2018_11_14: {
      uid: 'paraguay_protected_areas_2018_11_14__development',
      layergroupid: 'p2cs-sei@58c20a29@fdf353b181f5b78df49f77e604882d26:1542212474275'
    },
    paraguay_indigenous_areas_2018_11_14: {
      uid: 'paraguay_indigenous_areas_2018_11_14__development',
      layergroupid: 'p2cs-sei@254acf53@44edbbaac21d2dd619d147d0993f6b7f:1542212565695'
    },
    py_deforestation_2013_2017_20190131: {
      uid: 'py_deforestation_2013_2017_20190131__development',
      layergroupid: 'p2cs-sei@c8b99dd7@cbb68d33432adf3f69b686127104af27:1548926222884'
    },
    colombia_regional_autonomous_corps: {
      uid: 'colombia_regional_autonomous_corps__development',
      layergroupid: 'p2cs-sei@358d2853@4a2c3386345ec46663b8e4cf799f379b:1536313111531'
    },
    colombia_protected_areas: {
      uid: 'colombia_protected_areas__development',
      layergroupid: 'p2cs-sei@35f6976d@f87a506e2b6d20be42fd3572616fb833:1536312121956'
    },
    ar_provinces_mainland_20191122: {
      uid: 'ar_provinces_mainland_20191122__development',
      layergroupid: 'p2cs-sei@0a28a0d8@9915731691f519932a95ed42ab3e640f:1574445599212'
    },
    ar_biomes_20191113: {
      uid: 'ar_biomes_20191113__development',
      layergroupid: 'p2cs-sei@7aaf865a@1165b1c0214689a65a4556aaaf9d577d:1573645666401'
    },
    argentina_protected_areas_20191117: {
      uid: 'argentina_protected_areas_20191117__development',
      layergroupid: 'p2cs-sei@3dce118e@d8ab389137c04c540ae66807dea570c0:1574065380303'
    }
  },
  sandbox: {
    brazil_biomes: {
      uid: 'brazil_biomes__sandbox',
      layergroupid: 'p2cs-sei@c93b6cad@5a3d352564249dd7eaf1f5a2271b471d:1536754747512'
    },
    brazil_indigenous_areas: {
      uid: 'brazil_indigenous_areas__sandbox',
      layergroupid: 'p2cs-sei@99f56118@ef8eae3b879a710a3772c7a5f1e34eae:1538034854446'
    },
    paraguay_ecoregions_2018_11_14: {
      uid: 'paraguay_ecoregions_2018_11_14__sandbox',
      layergroupid: 'p2cs-sei@8d7b2903@e25bfafe50ad1cde7cee552c474151bb:1543380503816'
    },
    colombia_regional_autonomous_corps: {
      uid: 'colombia_regional_autonomous_corps__sandbox',
      layergroupid: 'p2cs-sei@ac06e412@8920938abbeed970d70f57bec86dcd00:1536313111531'
    },
    colombia_protected_areas: {
      uid: 'colombia_protected_areas__sandbox',
      layergroupid: 'p2cs-sei@dba9560a@d9b798b42ae0e7bbb677bfbe46d49413:1536312121956'
    },
    brazil_states: {
      uid: 'brazil_states__sandbox',
      layergroupid: 'p2cs-sei@813fddd3@cc7c9866165bd98a1fdd4113ec31ac49:1536754740910'
    },
    brazil_water_scarcity: {
      uid: 'brazil_water_scarcity__sandbox',
      layergroupid: 'p2cs-sei@51aab8e1@4ee3434d572f8071c4ee8395cd84c069:1536754755124'
    },
    brazil_protected: {
      uid: 'brazil_protected__sandbox',
      layergroupid: 'p2cs-sei@94358e00@27478e79b3971e23f86bccc8aae4b0e1:1537979981544'
    },
    brazil_defor_alerts: {
      uid: 'brazil_defor_alerts__sandbox',
      layergroupid: 'p2cs-sei@d3572a6b@119855d12a08daf809c7911fb721a04c:1538401614852'
    },
    paraguay_protected_areas_2018_11_14: {
      uid: 'paraguay_protected_areas_2018_11_14__sandbox',
      layergroupid: 'p2cs-sei@6f1f4672@d067ffc51eb3571426f0270c531418f4:1542212474275'
    },
    paraguay_indigenous_areas_2018_11_14: {
      uid: 'paraguay_indigenous_areas_2018_11_14__sandbox',
      layergroupid: 'p2cs-sei@c9296fcb@361d88be2a45cce2c7fd5f15e667d1ae:1542212565695'
    },
    py_deforestation_2013_2017_20190131: {
      uid: 'py_deforestation_2013_2017_20190131__sandbox',
      layergroupid: 'p2cs-sei@1d3f021a@0117a7789472bd8d3ec12e4d5600e7ab:1548926222884'
    }
  },
  demo: {
    ar_biomes_20191113: {
      uid: 'ar_biomes_20191113__demo',
      layergroupid: 'p2cs-sei@e3bf82ba@761a22bad4e22bec918c58d95bdf6eaa:1573645666401'
    },
    argentina_protected_areas_20191117: {
      uid: 'argentina_protected_areas_20191117__demo',
      layergroupid: 'p2cs-sei@951e6b9a@1b0dcf13fd35e7e26b4116bdceb16cd1:1574065380303'
    },
    ar_provinces_mainland_20191122: {
      uid: 'ar_provinces_mainland_20191122__demo',
      layergroupid: 'p2cs-sei@b5a5fb70@f200cb95920b944cb550ca4bac3882d2:1574445599212'
    }
  },
  indonesiademo: {
    id_provinces: {
      uid: 'id_provinces__indonesiademo',
      layergroupid: 'p2cs-sei@31274b67@3f435dd170b19c94f677d474bcd298e4:1560524731493'
    }
  }
};
